// User
export const ERROR_RECEIVE_USER = 'ERROR_RECEIVE_USER';
export const REQUEST_USER = 'REQUEST_USER';
export const RECEIVE_USER = 'RECEIVE_USER';

export const ERROR_SIGN_IN = 'ERROR_SIGN_IN';
export const REQUEST_SIGN_IN = 'REQUEST_SIGN_IN';
export const SUCCESS_SIGN_IN = 'SUCCESS_SIGN_IN';

export const ERROR_SIGN_UP = 'ERROR_SIGN_UP';
export const REQUEST_SIGN_UP = 'REQUEST_SIGN_UP';
export const SUCCESS_SIGN_UP = 'SUCCESS_SIGN_UP';

export const REQUEST_SIGN_OUT = 'REQUEST_SIGN_OUT';

// Exercise
export const ERROR_RECEIVE_EXERCISES = 'ERROR_RECEIVE_EXERCISES';
export const REQUEST_EXERCISES = 'REQUEST_EXERCISES';
export const RECEIVE_EXERCISES = 'RECEIVE_EXERCISES';

export const ADD_EXERCISE = 'ADD_EXERCISE';
export const EDIT_EXERCISE = 'EDIT_EXERCISE';
export const DELETE_EXERCISE = 'DELETE_EXERCISE';
export const REQUEST_DELETE_EXERCISE = 'REQUEST_DELETE_EXERCISE';
export const ERROR_DELETE_EXERCISE = 'ERROR_DELETE_EXERCISE';

